"""Generate static neural-voice MP3s. Requires Node.js and edge-tts==7.2.8."""

import asyncio
import hashlib
import json
from pathlib import Path
import subprocess

import edge_tts

ROOT = Path(__file__).resolve().parent
VOICE = "zh-CN-XiaoxiaoNeural"
RATE = "-8%"


async def main():
    result = subprocess.run(
        ["node", "-e", """
const fs = require('node:fs');
const vm = require('node:vm');
const context = {window: {}};
vm.createContext(context);
for (const file of ['words.js', 'voice-lines.js']) {
  vm.runInContext(fs.readFileSync(file, 'utf8'), context);
}
const {HANZI_WORDS: words, HANZI_SPEECH: lines} = context.window;
const texts = words.flatMap(word => [lines.lesson(word), lines.prompt(word), lines.retry(word)]);
texts.push(...lines.praise, lines.retryPraise, lines.finish);
process.stdout.write(JSON.stringify([...new Set(texts)]));
"""], cwd=ROOT, check=True, capture_output=True, text=True,
    )
    texts = json.loads(result.stdout)
    folder = ROOT / "audio"
    folder.mkdir(exist_ok=True)
    manifest = {}
    # Sequential generation avoids bursts against the speech service.
    for index, text in enumerate(texts):
        digest = hashlib.sha256(f"{VOICE}|{RATE}|{text}".encode()).hexdigest()[:20]
        name = f"{digest}.mp3"
        destination = folder / name
        if not destination.exists() or destination.stat().st_size < 1000:
            temporary = folder / f"{name}.part"
            for attempt in range(3):
                try:
                    await asyncio.wait_for(
                        edge_tts.Communicate(text, VOICE, rate=RATE).save(str(temporary)),
                        timeout=45,
                    )
                    if temporary.stat().st_size < 1000:
                        raise RuntimeError("Empty audio response")
                    temporary.replace(destination)
                    break
                except Exception:
                    temporary.unlink(missing_ok=True)
                    if attempt == 2:
                        raise
                    await asyncio.sleep(2)
        manifest[text] = f"audio/{name}"
        print(f"{index + 1}/{len(texts)} {text}", flush=True)
    output = "// Generated by generate-audio.py; do not edit manually.\n"
    output += "window.HANZI_AUDIO = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n"
    (ROOT / "audio-manifest.js").write_text(output, encoding="utf-8")
    (folder / "metadata.json").write_text(json.dumps({
        "provider": "Microsoft Edge online neural TTS", "voice": VOICE,
        "rate": RATE, "generator": "edge-tts 7.2.8", "clips": len(manifest),
    }, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    asyncio.run(main())
